### ISSUE TITLE
CI never exercises the declared transformers floor, so a >=4.56-only kwarg passes 12/12

### ISSUE THREAD

**Issue by MakazhanAlpamys** [MakazhanAlpamys/Soup#478]
Found while reviewing #471, which was caught by hand rather than by CI. The PR is fine; the gap is ours.

## The gap

`pyproject.toml` declares:

```
transformers>=4.36.0,<5.0.0
```

CI installs with `pip install -e ".[dev]"`, which resolves to the **newest** satisfying version (4.57.x today). So the floor of our own declared range is **never executed**. A change that works on 4.57 and is a hard `TypeError` on 4.55 goes green on all 12 cells.

That is not hypothetical — it is exactly what happened in #471:

```
transformers 4.55.4   dtype='auto'  -> TypeError: __init__() got an unexpected keyword argument 'dtype'
transformers 4.57.6   dtype='auto'  -> loaded
```

`dtype=` is the >= 4.56 rename of `torch_dtype=`. Twenty minor versions inside our declared support would have failed at model load, before step 0, on text/vision/audio/QLoRA alike.

## Why it matters more than a version skew usually would

**pip does not upgrade an already-satisfying dependency.** Someone sitting on 4.55.4 who runs `pip install soup-cli[train]` keeps 4.55.4 — our pin is satisfied. That is the older-image Colab/Kaggle population, i.e. the same fleet #385/#387 was about.

`grep -rn "4.56" .` returns nothing: no test, no comment, no constraint anywhere records that a floor exists to respect.

## Two things this is NOT

- Not an argument for raising the floor. Deciding `>=4.56` is a dependency-policy call with its own cost (it drops those users rather than supporting them).
- Not solved by a lockfile. `soup env lock` records what a user *has*; this is about what our pin *promises*.

## Acceptance

- [ ] Something exercises the declared floor. Cheapest credible form is one CI cell that installs `transformers==4.36.0` (or the lowest version that actually resolves with our other pins) and runs a targeted subset — model-construction paths, not the full 18k suite.
- [ ] It must FAIL on a `dtype=`-style regression. Verify by writing the failure first: put `dtype=` back at one `from_pretrained` site and confirm the new cell goes red while the existing 12 stay green. A floor cell that cannot fail is worse than none, because it looks like coverage.
- [ ] If a true floor run is impractical (older transformers may not resolve against current torch/peft/trl), the fallback is a static guard: a test asserting no `from_pretrained` call site uses a kwarg introduced after our floor. Narrower, but it would have caught #471.

## Related

The same class already bit us the other way in #326 (`max_prompt_length` removed by trl in stages, a version table wrong twice) — the answer there was to probe **capabilities** rather than versions. Worth considering here: `"torch_dtype" if "dtype" not in signature else "dtype"` is uglier than a floor cell but has no version table to get wrong.

**Comment by AchuthReddy-16** [comment]
I’d like to take this.

I’ll add one focused Ubuntu/Python floor job rather than expanding the full 12-cell matrix. The job will use explicit constraints, assert the installed Transformers version, and include a fail-first regression proving a `dtype=`-only call fails below 4.56 while the existing matrix remains green.

I’ll first resolve the dependency-floor mismatch: Soup declares `transformers>=4.36`, but the currently resolved `trl` requires Transformers 4.56+. If the declared floor cannot be installed with the supported dependency range, I’ll document the exact resolver conflict and use the issue’s static compatibility guard fallback rather than labeling 4.55.4 as the declared floor.

**Comment by MakazhanAlpamys** [comment]
Shipped in #489 by **@AchuthReddy-16** (on `main`, out in the next release).

**This issue was filed as CI hygiene and turned out to be a live, shipped breakage.** Twelve production `from_pretrained` sites passed `dtype=` — the transformers `>=4.56` rename of `torch_dtype=` — so `soup chat`, `soup diff`, `soup export`, `soup infer`, `soup merge` and `soup serve`, plus layer streaming and MoLE serving, **failed at model load on every transformers between our declared floor and 4.55**. That is the whole lower half of the range this project claims to support, and the older-image Colab/Kaggle population from #385/#387.

Measured rather than reasoned, because two independent reviews disagreed on whether the wrong spelling raises or is silently ignored. `transformers==4.46.1` in an isolated install, against a locally-built bf16 checkpoint:

```
dtype=torch.float16        -> TypeError: LlamaForCausalLM.__init__() got an
                              unexpected keyword argument 'dtype'
torch_dtype=torch.float16  -> OK, resident dtype = torch.float16
(no kwarg)                 -> OK, resident dtype = torch.float32
```

The mechanism: `configuration_utils.py` consumes an extra kwarg only `if hasattr(config, key)`. There is no `dtype` attribute before 4.56, so it survives into the returned `model_kwargs` and reaches `cls(config, **model_kwargs)` — a `TypeError` from the model's `__init__`, not a config attribute quietly set. The third line independently re-confirms #339's premise as a side effect: no kwarg at all means a bf16 checkpoint loads as fp32.

All twelve sites now use `torch_dtype=`, which predates the 4.36 floor and is explicitly retained for backwards compatibility at the 4.57 ceiling — the one spelling correct across the entire declared pin.

**Two guards, and the split between them matters:**

- `tests/test_transformers_floor_compat.py` — a static AST scan that fails if any production `AutoModel*.from_pretrained` uses `dtype=`. It runs in **all thirteen cells**, so it does not depend on the floor job being reached or staying green. This is what would have caught #471.
- a `transformers-floor` job pinning `transformers 4.46.1` + `trl 0.14.0`, asserting both exact versions and running `pip check`.

**Stated plainly, since the PR notes read otherwise:** the floor job proves *resolvability* at the floor pair, not runtime behaviour — neither selected test imports `transformers`, so the pinned install is never exercised by a model construction. The static scan is the real guard, and it is the documented fallback in this issue's own acceptance criteria.

On the pin itself: `transformers==4.36.0` genuinely cannot resolve — `trl 0.14.0` requires `>=4.46.0` and every file of 4.46.0 is yanked — so 4.46.1 is the lowest installable version. @AchuthReddy-16 documented that rather than quietly relabelling a convenient version as "the floor"; both claims were verified against PyPI metadata independently.

Two follow-ups filed rather than blocking the fix: **#494** (the floor version is hardcoded in three places and derived from none, so a pin bump silently leaves CI testing an unrelated version) and **#495** (the scanner matches only `AutoModel*`, so a concrete class such as `WhisperForConditionalGeneration` is invisible to it — both live Whisper sites are clean today).
